# Generated by Django 4.2.7 on 2023-11-28 11:23

import Costumers.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_identification_front', models.FileField(upload_to=Costumers.utils.save_id_document)),
                ('document_identification_back', models.FileField(upload_to=Costumers.utils.save_id_document)),
                ('proof_address', models.FileField(upload_to=Costumers.utils.save_proof_address)),
                ('first_receipt', models.FileField(upload_to=Costumers.utils.save_acount_tenant)),
                ('second_receipt', models.FileField(upload_to=Costumers.utils.save_acount_tenant)),
                ('third_receipt', models.FileField(upload_to=Costumers.utils.save_acount_tenant)),
                ('finish', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costumers.tenantmodel')),
            ],
        ),
    ]
