# Generated by Django 4.2.7 on 2023-11-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0002_tenantdocumentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasepropertymodel',
            name='lessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costumers.lessormodel'),
        ),
    ]
