# Generated by Django 4.2.7 on 2023-11-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0004_alter_lessormodel_address_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmodel',
            name='house_in_perspective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costumers.leasepropertymodel'),
        ),
    ]
