# Generated by Django 4.2.7 on 2023-12-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0010_alter_lessormodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessormodel',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
