# Generated by Django 4.2.7 on 2023-12-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0011_alter_lessormodel_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasepropertymodel',
            name='cfe_service_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leasepropertymodel',
            name='water_service_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lessormodel',
            name='birthday',
            field=models.DateField(),
        ),
    ]
