# Generated by Django 4.2.7 on 2023-12-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0014_remove_lessormodel_membership_membershipmodels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantmodel',
            name='membership',
        ),
        migrations.AddField(
            model_name='tenantmodel',
            name='membership_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costumers.membershipmodels'),
        ),
    ]
