# Generated by Django 4.2.7 on 2023-12-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0015_remove_tenantmodel_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapaymentmodel',
            name='active_account',
            field=models.BooleanField(default=False),
        ),
    ]
