# Generated by Django 4.2.7 on 2023-12-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0016_datapaymentmodel_active_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapaymentmodel',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
