# Generated by Django 4.2.7 on 2023-12-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0017_datapaymentmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasepropertymodel',
            name='property_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
